image: ruby:3.0

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

cache:
  paths:
    - vendor/

pages:
  script:
    - gem install bundler
    - bundle install --path vendor
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public